In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = np.loadtxt("0000000000002417_training_boston_x_y_train.csv", delimiter = ",")

#train_data = pd.read_csv("0000000000002417_training_boston_x_y_train.csv", delimiter = ",")
train_data.shape

(379, 14)

In [3]:
test_data = np.genfromtxt("0000000000002417_test_boston_x_test.csv", delimiter = ",")

#test_data = pd.read_csv("0000000000002417_test_boston_x_test.csv", delimiter = ",")
test_data.shape

(127, 13)

In [4]:
train_data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [5]:
test_data

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [6]:
X_train = train_data[:, :-1]
X_train[0]

array([-0.40784991, -0.48772236, -1.2660231 , -0.27259857, -0.57613394,
        1.23997392,  0.84012202, -0.52026428, -0.75292215, -1.27835435,
       -0.30309415,  0.41057102, -1.09799011])

In [7]:
X_train.shape

(379, 13)

In [8]:
X_test = test_data[:, :]
X_test[0]

array([ 2.91816626, -0.48772236,  1.01599907, -0.27259857,  0.36544404,
       -1.60934343,  1.11749449, -1.04849446,  1.66124525,  1.53092646,
        0.80657583, -1.59755122,  1.04106182])

In [22]:
X_test.shape

(127, 13)

In [23]:
x = X_train
#x = np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)
Y_train = X_train[:, -1]
y = Y_train
print(x.shape)
print(y.shape)

(379, 13)
(379,)


In [17]:
'''
from sklearn.datasets import load_boston
import numpy as np
data=load_boston()
data
'''

'\nfrom sklearn.datasets import load_boston\nimport numpy as np\ndata=load_boston()\ndata\n'

In [11]:
def step_gradient(X, Y, learning_rate, m):
    m_slope = np.zeros(len(X[0]))
    M = len(X)
    for i in range(M):
        x = X[i]
        y = Y[i]
        for j in range(len(x)):
            m_slope[j] += -(2 / M) * (y - sum(m * x)) * x[j]
    new_m = m - learning_rate * m_slope
    return new_m

In [12]:
def gd(X, Y, learning_rate, n_iterations):
    m = np.zeros(len(X[0]))
    for i in range(n_iterations):
        m = step_gradient(X, Y, learning_rate, m)
        print(i, "Cost : ", cost(X, Y, m))
    return m

In [13]:
def cost(X, Y, m):
    tot_cost = 0
    M = len(X)
    for i in range(M):
        tot_cost += (1 / M) * ((Y[i] - (m * x[i]).sum()) ** 2)
    return tot_cost

In [14]:
def gredient_descent(x, y):
    data = np.loadtxt("data.csv", delimiter = ",")
    learning_rate = 0.005
    n_iterations = 10
    #x = np.append(x, np.ones(len(x)).reshape(-1, 1), axis = 1)
    m = gd(x, y, learning_rate, n_iterations)
    print(i,"Cost :",cost(m,x,y))
    return m

In [32]:
def run(x, y):
    #x = X_train
    x = np.append(x, np.ones(len(x)).reshape(-1,1),axis=1)
    #y = X_train[:, -1:]
    m = gredient_descent(x, y)
    print(m)

In [17]:
#run()

In [33]:
# feature scaling
# taking squre of each feature
#'''
x = train_data[:, :-1]
x[0]
#'''

array([-0.40784991, -0.48772236, -1.2660231 , -0.27259857, -0.57613394,
        1.23997392,  0.84012202, -0.52026428, -0.75292215, -1.27835435,
       -0.30309415,  0.41057102, -1.09799011])

In [34]:
#'''
y = train_data[:, -1]
y[0]
#'''

37.9

In [35]:
# appending sq to respective column
#'''
sq = []
for i in x:
    sq.append(i**2)
    #print(sq)
sq = np.array(sq)
x = np.append(x, sq, axis = 1) #means column
x[0]
#'''

array([-0.40784991, -0.48772236, -1.2660231 , -0.27259857, -0.57613394,
        1.23997392,  0.84012202, -0.52026428, -0.75292215, -1.27835435,
       -0.30309415,  0.41057102, -1.09799011,  0.16634155,  0.2378731 ,
        1.60281449,  0.07430998,  0.33193032,  1.53753532,  0.70580501,
        0.27067492,  0.56689176,  1.63418984,  0.09186606,  0.16856856,
        1.20558228])

In [36]:
x.shape

(379, 26)

In [19]:
# just try
'''
features = []
for i in range(len(x[0])):
    for j in range(i,len(x[0])):
        for k in range(j,len(x[0])):
            features.append(x[:,i]*x[:,j]*x[:,k])
features = np.array(features)
for i in features:
    x=np.append(x,i.reshape(-1,1),axis=1)
print(x.shape)
print(x)
#'''

(379, 468)
[[-0.40784991 -0.48772236 -1.2660231  ... -0.18508661  0.49497715
  -1.32371742]
 [-0.40737368 -0.48772236  0.24705682 ... -0.04412552  0.07887577
  -0.14099296]
 [ 0.1251786  -0.48772236  1.01599907 ... 12.8386773  -3.01392315
   0.70752871]
 ...
 [-0.40831101 -0.48772236  0.24705682 ... -0.03683424  0.03705351
  -0.03727409]
 [-0.41061997 -0.48772236 -1.15221381 ... -0.03076159  0.11272547
  -0.41308112]
 [ 0.34290895 -0.48772236  1.01599907 ... -0.20441415  0.71605641
  -2.50832339]]


In [37]:
from sklearn import preprocessing

#x = np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)

scaler = preprocessing.StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
#m = gredient_descent(x, y)
print(x.shape)
print(x)

(379, 26)
[[-0.40098068 -0.49042688 -1.28149216 ... -0.68816762 -0.28011888
   0.11743628]
 [-0.40053396 -0.49042688  0.20753471 ... -0.74821148 -0.30738521
  -0.50280925]
 [ 0.09900799 -0.49042688  0.96425328 ... -0.26401169  4.35364339
  -0.15567276]
 ...
 [-0.40141319 -0.49042688  0.20753471 ... -0.74821148 -0.29909084
  -0.60852403]
 [-0.40357903 -0.49042688 -1.16949207 ... -0.36520097 -0.32153268
  -0.31450873]
 [ 0.30324229 -0.49042688  0.96425328 ... -0.26401169 -0.28601598
   0.54247549]]


In [38]:
m_new = run(x, y)

ValueError: operands could not be broadcast together with shapes (27,) (26,) 

In [46]:
'''
sq = []
for i in X_test:
    sq.append(i**2)
sq = np.array(sq)
X_test = np.append(X_test, sq, axis = 1)
X_test[0]
'''

'\nsq = []\nfor i in X_test:\n    sq.append(i**2)\nsq = np.array(sq)\nX_test = np.append(X_test, sq, axis = 1)\nX_test[0]\n'

In [108]:
#scaler.fit(X_test)
X_test = scaler.transform(X_test)
X_test[0]

array([ 2.71887193, -0.49042688,  0.96425328, -0.28784917,  0.33723016,
       -1.64178699,  1.09674705, -1.02022479,  1.5941481 ,  1.45994481,
        0.78816582, -1.55922624,  1.00848766,  0.29294666, -0.28997482,
        0.28510189, -0.28784917, -0.18671511, -0.7519154 ,  0.80899157,
       -0.43038219,  1.60899318,  1.45364388,  0.38674732, -0.09779468,
        0.05623524])

In [109]:
#X_test = np.append(X_test, np.ones(len(X_test)).reshape(-1, 1), axis = 1)
X_test[0]

array([ 2.71887193, -0.49042688,  0.96425328, -0.28784917,  0.33723016,
       -1.64178699,  1.09674705, -1.02022479,  1.5941481 ,  1.45994481,
        0.78816582, -1.55922624,  1.00848766,  0.29294666, -0.28997482,
        0.28510189, -0.28784917, -0.18671511, -0.7519154 ,  0.80899157,
       -0.43038219,  1.60899318,  1.45364388,  0.38674732, -0.09779468,
        0.05623524])

In [110]:
Y_pred = []
for i in X_test:
    Y_pred.append(sum(m*i))
    
for i in Y_pred:
    print(i)
    
Y_pred = np.array(Y_pred)

-3.2835897243274488
1.6275747295936065
0.16107086881607802
1.7330456160625594
0.07180650747478616
-3.77031497122982
1.4884378963275944
1.061658804401419
-0.030073561561476517
0.730128192419933
1.141229386266732
-0.13127988963574283
0.9737505086219141
0.4693510770254895
2.8633331227903915
1.706659334516561
1.533767358428005
1.1378275466880474
1.3251899334656412
1.4908468370423982
0.2307623576280213
0.0016710121808888104
0.8439410937997629
2.590702659062502
3.505967832022413
-2.3376173708959316
0.3418822330175094
2.2598444103321835
0.6090267619083578
1.4792583850351084
-0.10856480920872445
1.3939800316030746
0.3625715545908725
1.0591386912801228
-2.649660785751849
0.9807631502493173
1.5086273135258168
-0.14384092834658296
1.3440996753566798
-4.105536727771081
-4.318556921543816
1.8686017769573011
2.9662537459806524
-0.8989080035209112
-1.6019847409983174
-4.930825015571724
3.037606667458744
0.5890746536486415
3.5560973590103817
-2.295593720104293
-2.249176688612957
4.3093836685976
-2.258

In [111]:
np.savetxt(X = Y_pred, fname = "Predicted.csv", delimiter = ",", fmt = "%.5f")